### ISSUE TITLE
[BUG] Read stackoverflow

### ISSUE THREAD

**Issue by superhx** [AutoMQ/automq#1037]
![image](https://github.com/AutoMQ/automq/assets/5719209/dc7d0080-6b51-4c96-99a1-329748cf4dd7)

**Comment by Chillax-0v0** [comment]
Caused by #1011 

Details:
Let 2 parts of stream 1 in LogCache: [0, 10], [100, 200]
- Call `LogCache#get` with (streamId=1, start=5, end=20, max=100) will return an empty list, as records [10, 20] not in LogCache.
- However, Call `LogCache#getFirstRecordBaseOffset` with (streamId=1, start=5, end=20, and max=1 set by `getFirstRecordBaseOffset`) will return the record at offset=5.
This will cause mismatches between `get` and `getFirst` and lead to infinite recursion.

Revert #1011 in #1038
