### ISSUE TITLE
You should not be spamming people about this

### ISSUE THREAD

**Issue by marcosscriven** [AutoMQ/automq#1974]
Who gave you permission to spam a load of people about this repo?

Why provide an "unsubscribe" link in a list I did not subscribe to in the first place?

**Comment by KaimingWan** [comment]
Hi @marcosscriven . Thank you for the feedback. I'm sorry that my colleague has disturbed you. He just wanted to make friends with some like-minded developers. That was just a regular email, you don't need to specifically unsubscribe, because you never subscribed in the first place. If you don't respond, I don't think he will send you any more information, because you might indeed have no interest in us. 

I will close the issue now. If you have any other thoughts, you can join our Slack channel and chat with me, I would be happy to answer any of your questions, thank you.


Slack: https://join.slack.com/t/automq/shared_invite/zt-29h17vye9-thf31ebIVL9oXuRdACnOIA

**Comment by marcosscriven** [comment]
Here's the email - it clearly asks to click "unsubscribe"

![Screenshot 2024-09-02 at 07 03 57](https://github.com/user-attachments/assets/321e9b3c-65ed-4707-8e68-bd8feb9c0ca5)

**Comment by ceeeekay** [comment]
You should definitely not be spamming people about your project, whether it's a list email or not.

Anyone else that's here because they were spammed should report this project at https://github.com/contact/report-abuse?report=AutoMQ
