### ISSUE TITLE
[BUG] s3.block.cache.size config error

### ISSUE THREAD

**Issue by funky-eyes** [AutoMQ/automq#973]
### Version & Environment

![image](https://github.com/AutoMQ/automq-for-kafka/assets/19943636/b1054b3c-8d67-4e5d-b48b-22dede225035)

怀疑#946 中存在bug

启动命令中不设置s3.block.cache.size和s3.wal.cache.size时触发该异常

s3.block.cache.size变成了-1，然后s3.wal.cache.size=2g，机器配置为2c16g,将s3.block.cache.size设置为2g时，就会出现不允许二者相同的异常提示。

Suspected bug in https://github.com/AutoMQ/automq-for-kafka/pull/946

This exception is triggered when s3.block.cache.size and s3.wal.cache.size are not set in the startup command

S3.block.cache.size becomes -1, then s3.wal.cache.size = 2g, the machine configuration is 2c16g, and when s3.block.cache.size is set to 2g, the same exception prompt is not allowed.

### How to reproduce the issue?

1.
2.
3.

### Additional information

Please attach any relevant logs, backtraces, or metric charts.

**Comment by Chillax-0v0** [comment]
您好，感谢反馈！

这确实是一个 bug，它会导致在未设置 `s3.wal.cache.size`, `s3.block.cache.size` 或 `s3.wal.upload.threshold` 时，它们会被设置为 -1，而非我们期望的自动生成的值。手动指定前述的三个值可以绕过这个 bug。

同时，这个 bug 已经在 `main` 分支与 `1.0` 分支修复，详见 #959 #970 #971 。特别地，刚刚我们重新发布了 [Release 1.0.2](https://github.com/AutoMQ/automq/releases/tag/1.0.2)，该版本中也修复了本 bug，您可以使用它来继续体验。

再次感谢您的反馈，如有其他问题，欢迎讨论~

---

Hello, thank you for your feedback!

This is indeed a bug, which causes `s3.wal.cache.size`, `s3.block.cache.size`, or `s3.wal.upload.threshold` to be set to -1, instead of the expected auto-generated values when they are not set. This bug can be circumvented by manually specifying the aforementioned three values.

Meanwhile, this bug has been fixed in both the main branch and the 1.0 branch, as detailed in #959, #970, and #971. In particular, we have just re-released [Release 1.0.2](https://github.com/AutoMQ/automq/releases/tag/1.0.2), which also includes a fix for this bug. You can use this version to continue your experience.

Thank you again for your feedback, and if you have any other questions, please feel free to discuss them.

**Comment by funky-eyes** [comment]
我认为修复问题的版本应该释放一个子版本，而不是直接覆盖对应版本，这将会让问题排查和版本管理更加复杂和混乱，因为很可能出现此版本非彼版本的问题。
I think the version that fixes the problem should release a sub version instead of directly overwriting the corresponding version, which will make problem troubleshooting and version management more complex and chaotic, as it is likely to have issues with this version being different from that version.
